export const jobStatusOptions = [
  'Quote',
  'Work Order',
  'Completed',
  'Unsuccussfull',
]

export const yesNoOptions = ['Yes', 'No']
export const standardFinish = ['Smooth', 'Woodgrain', 'n/a']
export const standardTaper = ['LHS Vilo', 'RHS Vilo']
export const standardHardware = ['LHR <330mm', 'STD HR >330mm']
export const standardMotor = [
  'Refit Existing motor',
  'CAD Secure',
  'CAD Smart',
  'Ezilift',
  'Merlin Essential',
  'Merlin Elite',
  'Merlin Extreme',
  'Merlin Platinum',
  'Merlin Ultimate',
  'Superlift 1000nm',
  'Superlift 1200nm',
  'ATA Synchro',
  'ATA Tempo',
]
export const standardJambs = [
  '100x70x2500',
  '100x70x3000',
  '125x70x2500',
  '125x70x3000',
  '150x70x2500',
  '150x70x3000',
  '180x70x2500',
  '180x70x3000',
  'Custom',
]
export const standardCovers = [...standardJambs]
export const standardPelmet = [
  '220x50x3000',
  '220x50x5500',
  '250x50x3000',
  '250x50x5500',
  '300x50x3000',
  'Custom',
]
export const standardBrushSeals = [
  'No Brush Seals',
  'Perimeter Brush seals',
  'Side Brush seals',
]
export const standardEkr = ['Yes', 'Not required']
export const standardInsulation = ['Yes', 'No']
export const bdmStyle = ['BDM Flat', 'BDM Rib']
export const bdSectionalStyle = [
  'PFT Grange',
  'PFT Nullarbor',
  'PFT Seville',
  'PFT Statesman',
  'PFI Grange',
  'PFI Nullabor',
  'PFI Seville',
  'PFI Statesman',
]
export const csiSectionalStyle = ['CSI Grange', 'CSI Nullarbor', 'CSI Seville', 'CSI Statesman']
export const bdRadDomesticStyle = ['R1D Deluxe', 'R1P Rollmaster', 'R2L Traditional 0.4', 'R3W Squareline 0.5']
export const bdRadIndustrialStyle = ['R2F Firmador 0.4', 'R2i Industrial 0.5']
export const centurionSectionalStyle = ['Cosmopolitan', 'Georgian', 'Mediterranean', 'Regency', 'Settler']
export const centurionRadStyle = ['A-series', 'AA-series']
export const centurionBRadStyle = ['B-series', 'Option 2']
export const steelineSectionalStyle = ['Fineline', 'Flatline', 'Heritage', 'Ranch', 'Ribline', 'Stanford']
export const steelineRadStyle = ['A-series', 'AA-series']
export const danmarCustomStyle = [
  'Ali Batten',
  'Ali Castellated',
  'Ali Louvre',
  'Aliwood VJ',
  'Ali Woodlook + borders',
  'Ali Panel',
  'Bar Panel',
  'Barlite',
  'Barn Panel',
  'Carriage Panel',
  'Cedar Batten',
  'Clearlite',
  'exDF',
  'Glasslite',
  'Grille Panel',
  'Mini-orb',
  'Thermofine Ins',
  'Thermoflat Ins',
  'Twinlite',
]
export const metrolRadStyle = ['Domestic RAD', 'Option 2']
export const centurionColours = [
  'Dover white',
  'Surfmist',
  'Shale Grey',
  'Basalt',
  'Classic Cream',
  'Paper Bark',
  'Evening Haze',
  'Dune',
  'Jasper',
  'Woodland Grey',
  'Deep Ocean',
  'Monument',
  'Southerly (p/coated)',
  'Bluegum (p/coated)',
  'Windspray (p/coated)',
  'Gully (p/coated)',
  'Wallaby (p/coated)',
  'Night Sky (p/coated)',
  'Cottage Green (p/coated)',
  'Pale Eucalypt (p/coated)',
  'Manor Red (p/coated)',
]
export const standardColours = [
  'Basalt',
  'Bluegum',
  'Classic Cream',
  'Cottage Green',
  'Deep Ocean',
  'Dover White',
  'Dune',
  'Evening Haze',
  'Gully',
  'Ironstone',
  'Jasper',
  'Manor Red',
  'Monument',
  'Nightsky',
  'Pale Eucalypt',
  'Paperbark',
  'Shale Grey',
  'Southerly',
  'Surfmist',
  'Wallaby',
  'Windspray',
  'Woodland Grey',
]
export const bdmColours = [...standardColours, 'Custom']
export const danmarColours = [...standardColours, 'Custom']
export const steelineTimberlooks = ['Ashen Black Oak', 'Blushed Teak', 'Classic CEDAR', 'Caoba']
export const danmarTimberlooks = ['Dark Oak', 'Light Oak']
export const materialManufacturers = [
  'BDM Thermo',
  'B&D Sectional',
  'CSI Sectional',
  'B&D RAD Domestic',
  'B&D RAD Industrial',
  'Centurion Sectional',
  'Centurion RAD',
  'Centurion B RAD',
  'Steeline Sectional',
  'Steeline RAD',
  'Danmar Custom',
  'Metrol RAD',
]

export const manufacturerConfigs = {
  'BDM Thermo': [
    { name: 'style', label: 'Style', type: 'select', options: bdmStyle },
    { name: 'colour', label: 'Colour', type: 'select', options: bdmColours },
    { name: 'finish', label: 'Finish', type: 'select', options: standardFinish },
    { name: 'taper', label: 'Taper', type: 'select', options: standardTaper },
    { name: 'hardware', label: 'Hardware', type: 'select', options: standardHardware },
    { name: 'motor', label: 'Motor', type: 'select', options: standardMotor },
    { name: 'jambs', label: 'Jambs', type: 'select', options: standardJambs },
    { name: 'covers', label: 'Covers', type: 'select', options: standardCovers },
    { name: 'pelmet', label: 'Pelmet', type: 'select', options: standardPelmet },
    { name: 'brushSeals', label: 'Brush Seals', type: 'select', options: standardBrushSeals },
    { name: 'ekr', label: 'EKR', type: 'select', options: standardEkr },
  ],
  'B&D Sectional': [
    { name: 'style', label: 'Style', type: 'select', options: bdSectionalStyle },
    { name: 'colour', label: 'Colour', type: 'select', options: standardColours },
    { name: 'timberlook', label: 'Timberlook', type: 'select', options: ['CAOBA', 'CLASSIC CEDAR'] },
    { name: 'finish', label: 'Finish', type: 'select', options: standardFinish },
    { name: 'taper', label: 'Taper', type: 'select', options: standardTaper },
    { name: 'hardware', label: 'Hardware', type: 'select', options: standardHardware },
    { name: 'motor', label: 'Motor', type: 'select', options: standardMotor },
    { name: 'jambs', label: 'Jambs', type: 'select', options: standardJambs },
    { name: 'covers', label: 'Covers', type: 'select', options: standardCovers },
    { name: 'pelmet', label: 'Pelmet', type: 'select', options: standardPelmet },
    { name: 'brushSeals', label: 'Brush Seals', type: 'select', options: standardBrushSeals },
    { name: 'insulation', label: 'Insulation', type: 'select', options: standardInsulation },
    { name: 'ekr', label: 'EKR', type: 'select', options: standardEkr },
  ],
  'CSI Sectional': [
    { name: 'style', label: 'Style', type: 'select', options: csiSectionalStyle },
    { name: 'colour', label: 'Colour', type: 'select', options: standardColours },
    { name: 'timberlook', label: 'Timberlook', type: 'select', options: ['CAOBA', 'CLASSIC CEDAR'] },
    { name: 'finish', label: 'Finish', type: 'select', options: standardFinish },
    { name: 'taper', label: 'Taper', type: 'select', options: standardTaper },
    { name: 'hardware', label: 'Hardware', type: 'select', options: standardHardware },
    { name: 'motor', label: 'Motor', type: 'select', options: standardMotor },
    { name: 'jambs', label: 'Jambs', type: 'select', options: standardJambs },
    { name: 'covers', label: 'Covers', type: 'select', options: standardCovers },
    { name: 'pelmet', label: 'Pelmet', type: 'select', options: standardPelmet },
    { name: 'brushSeals', label: 'Brush Seals', type: 'select', options: standardBrushSeals },
    { name: 'insulation', label: 'Insulation', type: 'select', options: standardInsulation },
    { name: 'ekr', label: 'EKR', type: 'select', options: standardEkr },
  ],
  'B&D RAD Domestic': [
    { name: 'style', label: 'Style', type: 'select', options: bdRadDomesticStyle },
    { name: 'colour', label: 'Colour', type: 'select', options: standardColours },
    { name: 'finish', label: 'Finish', type: 'select', options: standardFinish },
    { name: 'taper', label: 'Taper', type: 'select', options: standardTaper },
    { name: 'hardware', label: 'Hardware', type: 'select', options: ['Brick Fix', 'Steel Fix'] },
    { name: 'locking', label: 'Locking', type: 'select', options: ['Centre Lift Lock', 'No Lock'] },
    { name: 'motor', label: 'Motor', type: 'select', options: ['Refit Existing motor', 'ATA GDO6', 'Merlin Weatherdrive', 'Merlin Essential', 'Merlin Elite', 'Grifco LR Drive', 'Superlift RDO6'] },
    { name: 'jambs', label: 'Jambs', type: 'select', options: standardJambs },
    { name: 'covers', label: 'Covers', type: 'select', options: standardCovers },
    { name: 'pelmet', label: 'Pelmet', type: 'select', options: standardPelmet },
    { name: 'brushSeals', label: 'Brush Seals', type: 'select', options: standardBrushSeals },
    { name: 'ekr', label: 'EKR', type: 'select', options: standardEkr },
  ],
  'B&D RAD Industrial': [
    { name: 'style', label: 'Style', type: 'select', options: bdRadIndustrialStyle },
    { name: 'colour', label: 'Colour', type: 'select', options: standardColours },
    { name: 'finish', label: 'Finish', type: 'select', options: standardFinish },
    { name: 'taper', label: 'Taper', type: 'select', options: standardTaper },
    { name: 'hardware', label: 'Hardware', type: 'select', options: ['Brick Fix', 'Steel Fix'] },
    { name: 'locking', label: 'Locking', type: 'select', options: ['Industrial floor lock', 'Waist high side locks', 'No locks'] },
    { name: 'manualDrive', label: 'Manual Drive', type: 'select', options: ['LHS Vilo Planetary', 'No Planetary'] },
    { name: 'motor', label: 'Motor', type: 'select', options: ['Refit Existing motor', 'Grifco LR drive', 'no motor'] },
    { name: 'jambs', label: 'Jambs', type: 'select', options: standardJambs },
    { name: 'covers', label: 'Covers', type: 'select', options: standardCovers },
    { name: 'pelmet', label: 'Pelmet', type: 'select', options: standardPelmet },
    { name: 'brushSeals', label: 'Brush Seals', type: 'select', options: standardBrushSeals },
    { name: 'ekr', label: 'EKR', type: 'select', options: standardEkr },
  ],
  'Centurion Sectional': [
    { name: 'style', label: 'Style', type: 'select', options: centurionSectionalStyle },
    { name: 'colour', label: 'Colour', type: 'select', options: centurionColours },
    { name: 'timberlook', label: 'Timberlook', type: 'select', options: ['CAOBA', 'CLASSIC CEDAR'] },
    { name: 'finish', label: 'Finish', type: 'select', options: standardFinish },
    { name: 'taper', label: 'Taper', type: 'select', options: standardTaper },
    { name: 'hardware', label: 'Hardware', type: 'select', options: standardHardware },
    { name: 'motor', label: 'Motor', type: 'select', options: standardMotor },
    { name: 'jambs', label: 'Jambs', type: 'select', options: standardJambs },
    { name: 'covers', label: 'Covers', type: 'select', options: standardCovers },
    { name: 'pelmet', label: 'Pelmet', type: 'select', options: standardPelmet },
    { name: 'brushSeals', label: 'Brush Seals', type: 'select', options: standardBrushSeals },
    { name: 'insulation', label: 'Insulation', type: 'select', options: standardInsulation },
    { name: 'ekr', label: 'EKR', type: 'select', options: standardEkr },
  ],
  'Centurion RAD': [
    { name: 'style', label: 'Style', type: 'select', options: centurionRadStyle },
    { name: 'colour', label: 'Colour', type: 'select', options: standardColours },
    { name: 'finish', label: 'Finish', type: 'select', options: standardFinish },
    { name: 'taper', label: 'Taper', type: 'select', options: standardTaper },
    { name: 'hardware', label: 'Hardware', type: 'select', options: ['Brick Fix', 'Steel Fix'] },
    { name: 'locking', label: 'Locking', type: 'select', options: ['Centre Lift Lock', 'No Lock'] },
    { name: 'manualDrive', label: 'Manual Drive', type: 'select', options: ['LHS Vilo Planetary', 'No Planetary'] },
    { name: 'motor', label: 'Motor', type: 'select', options: ['Refit Existing motor', 'ATA GDO6', 'Merlin Weatherdrive', 'Merlin Essential', 'Merlin Elite', 'Grifco LR Drive', 'Superlift RDO6'] },
    { name: 'jambs', label: 'Jambs', type: 'select', options: standardJambs },
    { name: 'covers', label: 'Covers', type: 'select', options: standardCovers },
    { name: 'pelmet', label: 'Pelmet', type: 'select', options: standardPelmet },
    { name: 'brushSeals', label: 'Brush Seals', type: 'select', options: standardBrushSeals },
    { name: 'ekr', label: 'EKR', type: 'select', options: standardEkr },
  ],
  'Centurion B RAD': [
    { name: 'style', label: 'Style', type: 'select', options: centurionBRadStyle },
    { name: 'colour', label: 'Colour', type: 'select', options: standardColours },
    { name: 'finish', label: 'Finish', type: 'select', options: standardFinish },
    { name: 'taper', label: 'Taper', type: 'select', options: standardTaper },
    { name: 'hardware', label: 'Hardware', type: 'select', options: ['Brick Fix', 'Steel Fix'] },
    { name: 'locking', label: 'Locking', type: 'select', options: ['Industrial floor lock', 'Waist high side locks', 'No locks'] },
    { name: 'manualDrive', label: 'Manual Drive', type: 'select', options: ['LHS Vilo Planetary', 'No Planetary'] },
    { name: 'motor', label: 'Motor', type: 'select', options: ['Refit Existing motor', 'ATA GDO6', 'Merlin Weatherdrive', 'Merlin Essential', 'Merlin Elite', 'Grifco LR Drive', 'Superlift RDO6'] },
    { name: 'jambs', label: 'Jambs', type: 'select', options: standardJambs },
    { name: 'covers', label: 'Covers', type: 'select', options: standardCovers },
    { name: 'pelmet', label: 'Pelmet', type: 'select', options: standardPelmet },
    { name: 'brushSeals', label: 'Brush Seals', type: 'select', options: standardBrushSeals },
    { name: 'ekr', label: 'EKR', type: 'select', options: standardEkr },
  ],
  'Steeline Sectional': [
    { name: 'style', label: 'Style', type: 'select', options: steelineSectionalStyle },
    { name: 'colour', label: 'Colour', type: 'select', options: standardColours },
    { name: 'timberlook', label: 'Timberlook', type: 'select', options: steelineTimberlooks },
    { name: 'finish', label: 'Finish', type: 'select', options: standardFinish },
    { name: 'taper', label: 'Taper', type: 'select', options: standardTaper },
    { name: 'hardware', label: 'Hardware', type: 'select', options: standardHardware },
    { name: 'locking', label: 'Locking', type: 'select', options: ['Centre Lift Lock', 'No Lock'] },
    { name: 'motor', label: 'Motor', type: 'select', options: standardMotor },
    { name: 'jambs', label: 'Jambs', type: 'select', options: standardJambs },
    { name: 'covers', label: 'Covers', type: 'select', options: standardCovers },
    { name: 'pelmet', label: 'Pelmet', type: 'select', options: standardPelmet },
    { name: 'brushSeals', label: 'Brush Seals', type: 'select', options: standardBrushSeals },
    { name: 'insulation', label: 'Insulation', type: 'select', options: standardInsulation },
    { name: 'ekr', label: 'EKR', type: 'select', options: standardEkr },
  ],
  'Steeline RAD': [
    { name: 'style', label: 'Style', type: 'select', options: steelineRadStyle },
    { name: 'colour', label: 'Colour', type: 'select', options: standardColours },
    { name: 'finish', label: 'Finish', type: 'select', options: standardFinish },
    { name: 'taper', label: 'Taper', type: 'select', options: standardTaper },
    { name: 'hardware', label: 'Hardware', type: 'select', options: ['Brick Fix', 'Steel Fix'] },
    { name: 'locking', label: 'Locking', type: 'select', options: ['Centre Lift Lock', 'No Lock'] },
    { name: 'motor', label: 'Motor', type: 'select', options: ['Refit Existing motor', 'ATA GDO6', 'Merlin Weatherdrive', 'Merlin Essential', 'Merlin Elite', 'Grifco LR Drive', 'Superlift RDO6'] },
    { name: 'jambs', label: 'Jambs', type: 'select', options: standardJambs },
    { name: 'covers', label: 'Covers', type: 'select', options: standardCovers },
    { name: 'pelmet', label: 'Pelmet', type: 'select', options: standardPelmet },
    { name: 'brushSeals', label: 'Brush Seals', type: 'select', options: standardBrushSeals },
    { name: 'ekr', label: 'EKR', type: 'select', options: standardEkr },
  ],
  'Danmar Custom': [
    { name: 'style', label: 'Style', type: 'select', options: danmarCustomStyle },
    { name: 'colour', label: 'Colour', type: 'select', options: danmarColours },
    { name: 'timberlook', label: 'Timberlook', type: 'select', options: danmarTimberlooks },
    { name: 'finish', label: 'Finish', type: 'select', options: standardFinish },
    { name: 'taper', label: 'Taper', type: 'select', options: standardTaper },
    { name: 'hardware', label: 'Hardware', type: 'select', options: standardHardware },
    { name: 'motor', label: 'Motor', type: 'select', options: standardMotor },
    { name: 'jambs', label: 'Jambs', type: 'select', options: standardJambs },
    { name: 'covers', label: 'Covers', type: 'select', options: standardCovers },
    { name: 'pelmet', label: 'Pelmet', type: 'select', options: standardPelmet },
    { name: 'brushSeals', label: 'Brush Seals', type: 'select', options: standardBrushSeals },
    { name: 'ekr', label: 'EKR', type: 'select', options: standardEkr },
  ],
  'Metrol RAD': [
    { name: 'style', label: 'Style', type: 'select', options: metrolRadStyle },
    { name: 'colour', label: 'Colour', type: 'select', options: standardColours },
    { name: 'finish', label: 'Finish', type: 'select', options: standardFinish },
    { name: 'taper', label: 'Taper', type: 'select', options: standardTaper },
    { name: 'hardware', label: 'Hardware', type: 'select', options: ['Brick Fix', 'Steel Fix'] },
    { name: 'locking', label: 'Locking', type: 'select', options: ['Centre Lift Lock', 'No Lock'] },
    { name: 'motor', label: 'Motor', type: 'select', options: ['Refit Existing motor', 'ATA GDO6', 'Merlin Weatherdrive', 'Merlin Essential', 'Merlin Elite', 'Grifco LR Drive', 'Superlift RDO6'] },
    { name: 'jambs', label: 'Jambs', type: 'select', options: standardJambs },
    { name: 'covers', label: 'Covers', type: 'select', options: standardCovers },
    { name: 'pelmet', label: 'Pelmet', type: 'select', options: standardPelmet },
    { name: 'brushSeals', label: 'Brush Seals', type: 'select', options: standardBrushSeals },
    { name: 'ekr', label: 'EKR', type: 'select', options: standardEkr },
  ],
}
