export const jobStatusOptions = [
  'Quote',
  'Work Order',
  'Completed',
  'Unsuccessful',
]

export const yesNoOptions = ['No', 'Yes']
export const standardFinish = ['Smooth', 'Woodgrain', 'n/a']
export const standardTaper = ['LHS Vilo', 'RHS Vilo']
export const standardHardware = ['LHR <330mm', 'STD HR >330mm']
export const standardMotor = [
  'Refit Existing motor',
  'CAD Secure',
  'CAD Smart',
  'Ezilift',
  'Merlin Essential',
  'Merlin Elite',
  'Merlin Extreme',
  'Merlin Platinum',
  'Merlin Ultimate',
  'Superlift 1000nm',
  'Superlift 1200nm',
  'ATA Synchro',
  'ATA Tempo',
]
export const standardJambs = [
  '100x70x2500',
  '100x70x3000',
  '125x70x2500',
  '125x70x3000',
  '150x70x2500',
  '150x70x3000',
  '180x70x2500',
  '180x70x3000',
  'Custom',
]
export const standardCovers = [...standardJambs]
export const standardPelmet = [
  '220x50x3000',
  '220x50x5500',
  '250x50x3000',
  '250x50x5500',
  '300x50x3000',
  'Custom',
]
export const standardBrushSeals = [
  'No Brush Seals',
  'Perimeter Brush seals',
  'Side Brush seals',
]
export const standardEkr = ['Yes', 'Not required']
export const standardInsulation = ['Yes', 'No']
export const bdmStyle = ['BDM Flat', 'BDM Rib']
export const bdSectionalStyle = [
  'PFT Grange',
  'PFT Nullarbor',
  'PFT Seville',
  'PFT Statesman',
  'PFI Grange',
  'PFI Nullabor',
  'PFI Seville',
  'PFI Statesman',
]
export const csiSectionalStyle = ['CSI Grange', 'CSI Nullarbor', 'CSI Seville', 'CSI Statesman']
export const bdRadDomesticStyle = ['R1D Deluxe', 'R1P Rollmaster', 'R2L Traditional 0.4', 'R3W Squareline 0.5']
export const bdRadIndustrialStyle = ['R2F Firmador 0.4', 'R2i Industrial 0.5']
export const centurionSectionalStyle = ['Cosmopolitan', 'Georgian', 'Mediterranean', 'Regency', 'Settler']
export const centurionRadStyle = ['A-series', 'AA-series']
export const centurionBRadStyle = ['B-series', 'Option 2']
export const steelineSectionalStyle = ['Fineline', 'Flatline', 'Heritage', 'Ranch', 'Ribline', 'Stanford']
export const steelineRadStyle = ['A-series', 'AA-series']
export const danmarCustomStyle = [
  'Ali Batten',
  'Ali Castellated',
  'Ali Louvre',
  'Aliwood VJ',
  'Ali Woodlook + borders',
  'Ali Panel',
  'Bar Panel',
  'Barlite',
  'Barn Panel',
  'Carriage Panel',
  'Cedar Batten',
  'Clearlite',
  'exDF',
  'Glasslite',
  'Grille Panel',
  'Mini-orb',
  'Thermofine Ins',
  'Thermoflat Ins',
  'Twinlite',
]
export const metrolRadStyle = ['Domestic RAD', 'Option 2']
export const centurionColours = [
  'Dover white',
  'Surfmist',
  'Shale Grey',
  'Basalt',
  'Classic Cream',
  'Paper Bark',
  'Evening Haze',
  'Dune',
  'Jasper',
  'Woodland Grey',
  'Deep Ocean',
  'Monument',
  'Southerly (p/coated)',
  'Bluegum (p/coated)',
  'Windspray (p/coated)',
  'Gully (p/coated)',
  'Wallaby (p/coated)',
  'Night Sky (p/coated)',
  'Cottage Green (p/coated)',
  'Pale Eucalypt (p/coated)',
  'Manor Red (p/coated)',
]
export const standardColours = [
  'Basalt',
  'Bluegum',
  'Classic Cream',
  'Cottage Green',
  'Deep Ocean',
  'Dover White',
  'Dune',
  'Evening Haze',
  'Gully',
  'Ironstone',
  'Jasper',
  'Manor Red',
  'Monument',
  'Nightsky',
  'Pale Eucalypt',
  'Paperbark',
  'Shale Grey',
  'Southerly',
  'Surfmist',
  'Wallaby',
  'Windspray',
  'Woodland Grey',
]
export const centurionDesignOptions = [
  'Sunset',
  'Waterton',
  'Rushton',
  'Sunrise',
  'Sherwood',
  'Stockton',
  'Cascade',
  'Plain',
]
export const steelineWindowTypeOptions = {
  Heritage: [
    'Ruston Heritage',
    'Sunray X 8 Heritage',
    'Sunray 2 x 4 Heritage',
    'Sherwood 4 x 2 Heritage',
    'Stockton Heritage',
    'Plain Heritage',
  ],
  Ranch: [
    'Ruston Ranch',
    'Sunray X 4 Ranch',
    'Sunray 2 X 2 Ranch',
    'Sherwood Ranch',
    'Stockton Ranch',
    'Stockford Ranch',
    'Plain Ranch',
  ],
  Stanford: [
    'Sunrise X 6 Stanford',
    'Sunrise X 3 Stanford',
    'Sherwood X 3 Stanford',
    'Colonial Stanford',
    'Plain Stanford',
  ],
}
export const bdmColours = [...standardColours, 'Custom']
export const danmarColours = [...standardColours, 'Custom']
export const steelineTimberlooks = ['Ashen Black Oak', 'Blushed Teak', 'Classic CEDAR', 'Caoba']
export const danmarTimberlooks = ['Dark Oak', 'Light Oak']
export const materialManufacturers = [
  'BDM Thermo',
  'B&D Sectional',
  'CSI Sectional',
  'B&D RAD Domestic',
  'B&D RAD Industrial',
  'Centurion Sectional',
  'Centurion RAD',
  'Centurion B RAD',
  'Steeline Sectional',
  'Steeline RAD',
  'Danmar Custom',
  'Metrol RAD',
]

export const manufacturerConfigs = {
  'BDM Thermo': [
    { name: 'style', label: 'Style', type: 'select', options: bdmStyle },
    { name: 'colour', label: 'Colour', type: 'select', options: bdmColours },
    { name: 'finish', label: 'Finish', type: 'select', options: standardFinish },
    { name: 'taper', label: 'Taper', type: 'select', options: standardTaper },
    { name: 'hardware', label: 'Hardware', type: 'select', options: standardHardware },
    { name: 'motor', label: 'Motor', type: 'text' },
    { name: 'jambs', label: 'Jambs', type: 'select', options: standardJambs },
    { name: 'covers', label: 'Covers', type: 'select', options: standardCovers },
    { name: 'pelmet', label: 'Pelmet', type: 'select', options: standardPelmet },
    { name: 'brushSeals', label: 'Brush Seals', type: 'select', options: standardBrushSeals },
    { name: 'ekr', label: 'EKR', type: 'select', options: standardEkr },
  ],
  'B&D Sectional': [
    { name: 'style', label: 'Style', type: 'select', options: bdSectionalStyle },
    { name: 'colour', label: 'Colour', type: 'select', options: standardColours },
    { name: 'timberlook', label: 'Timberlook', type: 'select', options: ['CAOBA', 'CLASSIC CEDAR'] },
    { name: 'finish', label: 'Finish', type: 'select', options: standardFinish },
    { name: 'taper', label: 'Taper', type: 'select', options: standardTaper },
    { name: 'hardware', label: 'Hardware', type: 'select', options: standardHardware },
    { name: 'motor', label: 'Motor', type: 'text' },
    { name: 'jambs', label: 'Jambs', type: 'select', options: standardJambs },
    { name: 'covers', label: 'Covers', type: 'select', options: standardCovers },
    { name: 'pelmet', label: 'Pelmet', type: 'select', options: standardPelmet },
    { name: 'brushSeals', label: 'Brush Seals', type: 'select', options: standardBrushSeals },
    { name: 'insulation', label: 'Insulation', type: 'select', options: standardInsulation },
    { name: 'ekr', label: 'EKR', type: 'select', options: standardEkr },
  ],
  'CSI Sectional': [
    { name: 'style', label: 'Style', type: 'select', options: csiSectionalStyle },
    { name: 'colour', label: 'Colour', type: 'select', options: standardColours },
    { name: 'timberlook', label: 'Timberlook', type: 'select', options: ['CAOBA', 'CLASSIC CEDAR'] },
    { name: 'finish', label: 'Finish', type: 'select', options: standardFinish },
    { name: 'taper', label: 'Taper', type: 'select', options: standardTaper },
    { name: 'hardware', label: 'Hardware', type: 'select', options: standardHardware },
    { name: 'motor', label: 'Motor', type: 'text' },
    { name: 'jambs', label: 'Jambs', type: 'select', options: standardJambs },
    { name: 'covers', label: 'Covers', type: 'select', options: standardCovers },
    { name: 'pelmet', label: 'Pelmet', type: 'select', options: standardPelmet },
    { name: 'brushSeals', label: 'Brush Seals', type: 'select', options: standardBrushSeals },
    { name: 'insulation', label: 'Insulation', type: 'select', options: standardInsulation },
    { name: 'ekr', label: 'EKR', type: 'select', options: standardEkr },
  ],
  'B&D RAD Domestic': [
    { name: 'style', label: 'Style', type: 'select', options: bdRadDomesticStyle },
    { name: 'colour', label: 'Colour', type: 'select', options: standardColours },
    { name: 'finish', label: 'Finish', type: 'select', options: standardFinish },
    { name: 'taper', label: 'Taper', type: 'select', options: standardTaper },
    { name: 'hardware', label: 'Hardware', type: 'select', options: ['Brick Fix', 'Steel Fix'] },
    { name: 'locking', label: 'Locking', type: 'select', options: ['Centre Lift Lock', 'No Lock'] },
    { name: 'motor', label: 'Motor', type: 'text' },
    { name: 'jambs', label: 'Jambs', type: 'select', options: standardJambs },
    { name: 'covers', label: 'Covers', type: 'select', options: standardCovers },
    { name: 'pelmet', label: 'Pelmet', type: 'select', options: standardPelmet },
    { name: 'brushSeals', label: 'Brush Seals', type: 'select', options: standardBrushSeals },
    { name: 'ekr', label: 'EKR', type: 'select', options: standardEkr },
  ],
  'B&D RAD Industrial': [
    { name: 'style', label: 'Style', type: 'select', options: bdRadIndustrialStyle },
    { name: 'colour', label: 'Colour', type: 'select', options: standardColours },
    { name: 'finish', label: 'Finish', type: 'select', options: standardFinish },
    { name: 'taper', label: 'Taper', type: 'select', options: standardTaper },
    { name: 'hardware', label: 'Hardware', type: 'select', options: ['Brick Fix', 'Steel Fix'] },
    { name: 'locking', label: 'Locking', type: 'select', options: ['Industrial floor lock', 'Waist high side locks', 'No locks'] },
    { name: 'manualDrive', label: 'Manual Drive', type: 'select', options: ['LHS Vilo Planetary', 'No Planetary'] },
    { name: 'motor', label: 'Motor', type: 'text' },
    { name: 'jambs', label: 'Jambs', type: 'select', options: standardJambs },
    { name: 'covers', label: 'Covers', type: 'select', options: standardCovers },
    { name: 'pelmet', label: 'Pelmet', type: 'select', options: standardPelmet },
    { name: 'brushSeals', label: 'Brush Seals', type: 'select', options: standardBrushSeals },
    { name: 'ekr', label: 'EKR', type: 'select', options: standardEkr },
  ],
  'Centurion Sectional': [
    { name: 'style', label: 'Style', type: 'select', options: centurionSectionalStyle },
    { name: 'colour', label: 'Colour', type: 'select', options: centurionColours },
    { name: 'taperRequired', label: 'Taper required', type: 'select', options: ['Yes', 'No'] },
    { name: 'lhsHight', label: 'LHS Height', type: 'number' },
    { name: 'rhsHight', label: 'RHS Height', type: 'number' },
    { name: 'finishedDoorHeight', label: 'Finished Door Height', type: 'number' },
    { name: 'finishedDoorWidth', label: 'Finished Door Width', type: 'number' },
    { name: 'windowDesign', label: 'Window Design', type: 'select', options: centurionDesignOptions },
    { name: 'g4LhrOrStd', label: 'G4 LHR / G4 STD', type: 'select', options: ['G4 LHR', 'G4 STD'] },
    { name: 'panelsOnly', label: 'Panels only', type: 'select', options: ['Yes', 'No'] },
    { name: 'opener', label: 'Opener', type: 'text' },
    { name: 'railSize', label: 'Rail Size', type: 'text' },
    { name: 'fitThermoGuardInsulation', label: 'Fit ThermoGuard Insulation', type: 'select', options: ['Yes', 'No'] },
    { name: 'windStrutsOnAllPanels', label: 'Wind Struts on all panels', type: 'select', options: ['Yes', 'No'] },
    { name: 'oversizeWeatherSeal', label: 'Oversize Weather Seal', type: 'select', options: ['Yes', 'No'] },
    { name: 'pelmet', label: 'Pelmet size', type: 'select', options: standardPelmet },
    { name: 'jambs', label: 'Jamb size', type: 'select', options: standardJambs },
    { name: 'coverColour', label: 'Cover colour', type: 'select', options: centurionDesignOptions },
    { name: 'woodgrainOrSmooth', label: 'Woodgrain or Smooth', type: 'select', options: ['Woodgrain', 'Smooth'] },
    { name: 'steelWrapForTransport', label: 'Steel Wrap for Transport', type: 'select', options: ['Yes', 'No'] },
    { name: 'motor', label: 'Motor', type: 'text' },
    { name: 'other', label: 'Other', type: 'text' },
    { name: 'ekr', label: 'EKR', type: 'select', options: standardEkr },
  ],
  'Centurion RAD': [
    { name: 'style', label: 'Style', type: 'select', options: centurionRadStyle },
    { name: 'colour', label: 'Colour', type: 'select', options: standardColours },
    { name: 'finish', label: 'Finish', type: 'select', options: standardFinish },
    { name: 'taperRequired', label: 'Taper required', type: 'select', options: ['Yes', 'No'] },
    { name: 'finishedDoorHeight', label: 'Finished Door Height', type: 'number' },
    { name: 'finishedDoorWidth', label: 'Finished Door Width', type: 'number' },
    { name: 'keyedAlike', label: 'Keyed Alike', type: 'select', options: ['Yes', 'No'] },
    { name: 'opener', label: 'Opener' },
    { name: 'planetaryGearKit', label: 'Planetary Gear Kit', type: 'select', options: ['LH', 'RH', 'NR'] },
    { name: 'fixingRequirement', label: 'Masonry or Steel fixing req', type: 'text' },
    { name: 'oversizeWeatherSeal', label: 'Oversize weather seal', type: 'select', options: ['Yes', 'No'] },
    { name: 'windLock', label: 'Wind Lock', type: 'select', options: ['Yes', 'No'] },
    { name: 'steelWrapForTransport', label: 'Steel Wrap for transport', type: 'select', options: ['Yes', 'No'] },
    { name: 'taper', label: 'Taper', type: 'select', options: standardTaper },
    { name: 'other', label: 'Other', type: 'text' },
    { name: 'hardware', label: 'Hardware', type: 'select', options: ['Brick Fix', 'Steel Fix'] },
    { name: 'locking', label: 'Locking', type: 'select', options: ['Centre Lift Lock', 'No Lock'] },
    { name: 'manualDrive', label: 'Manual Drive', type: 'select', options: ['LHS Vilo Planetary', 'No Planetary'] },
    { name: 'motor', label: 'Motor', type: 'text' },
    { name: 'jambs', label: 'Jambs', type: 'select', options: standardJambs },
    { name: 'covers', label: 'Covers', type: 'select', options: standardCovers },
    { name: 'pelmet', label: 'Pelmet', type: 'select', options: standardPelmet },
    { name: 'brushSeals', label: 'Brush Seals', type: 'select', options: standardBrushSeals },
    { name: 'ekr', label: 'EKR', type: 'select', options: standardEkr },
  ],
  'Centurion B RAD': [
    { name: 'style', label: 'Style', type: 'select', options: centurionBRadStyle },
    { name: 'colour', label: 'Colour', type: 'select', options: standardColours },
    { name: 'finish', label: 'Finish', type: 'select', options: standardFinish },
    { name: 'taper', label: 'Taper', type: 'select', options: standardTaper },
    { name: 'hardware', label: 'Hardware', type: 'select', options: ['Brick Fix', 'Steel Fix'] },
    { name: 'locking', label: 'Locking', type: 'select', options: ['Industrial floor lock', 'Waist high side locks', 'No locks'] },
    { name: 'manualDrive', label: 'Manual Drive', type: 'select', options: ['LHS Vilo Planetary', 'No Planetary'] },
    { name: 'motor', label: 'Motor', type: 'text' },
    { name: 'jambs', label: 'Jambs', type: 'select', options: standardJambs },
    { name: 'covers', label: 'Covers', type: 'select', options: standardCovers },
    { name: 'pelmet', label: 'Pelmet', type: 'select', options: standardPelmet },
    { name: 'brushSeals', label: 'Brush Seals', type: 'select', options: standardBrushSeals },
    { name: 'ekr', label: 'EKR', type: 'select', options: standardEkr },
  ],
  'Steeline Sectional': [
    { name: 'style', label: 'Style', type: 'select', options: steelineSectionalStyle },
    { name: 'colour', label: 'Colour', type: 'select', options: standardColours },
    { name: 'timberlook', label: 'Timberlook', type: 'select', options: steelineTimberlooks },
    { name: 'finish', label: 'Finish', type: 'select', options: standardFinish },
    { name: 'doorHeight', label: 'Door Height', type: 'number' },
    { name: 'doorWidth', label: 'Door Width', type: 'number' },
    { name: 'woodGrainOrSmooth', label: 'Wood Grain or Smooth', type: 'text' },
    { name: 'fittings', label: 'Fittings', type: 'select', options: ['LHR', 'STD'] },
    { name: 'keyedAlike', label: 'Keyed Alike', type: 'select', options: ['Yes', 'No'] },
    { name: 'keyedDifferent', label: 'Keyed Different', type: 'select', options: ['Yes', 'No'] },
    { name: 'shootBolts', label: 'Shoot Bolts', type: 'select', options: ['Yes', 'No'] },
    { name: 'windowType', label: 'Window Type', type: 'select', options: [] },
    { name: 'taperVilo', label: 'Taper (Vilo)', type: 'select', options: ['Yes', 'No'] },
    { name: 'notched', label: 'Notched', type: 'select', options: ['Yes', 'No'] },
    { name: 'steelWrapForTransport', label: 'Steel Wrap for Transport', type: 'select', options: ['Yes', 'No'] },
    { name: 'packForTransport', label: 'Pack for Transport', type: 'select', options: ['Yes', 'No'] },
    { name: 'hardware', label: 'Hardware', type: 'select', options: standardHardware },
    { name: 'locking', label: 'Locking', type: 'select', options: ['Centre Lift Lock', 'No Lock'] },
    { name: 'motor', label: 'Motor', type: 'text' },
    { name: 'jambs', label: 'Jambs', type: 'select', options: standardJambs },
    { name: 'covers', label: 'Covers', type: 'select', options: standardCovers },
    { name: 'pelmet', label: 'Pelmet', type: 'select', options: standardPelmet },
    { name: 'brushSeals', label: 'Brush Seals', type: 'select', options: standardBrushSeals },
    { name: 'insulation', label: 'Insulation', type: 'select', options: standardInsulation },
    { name: 'ekr', label: 'EKR', type: 'select', options: standardEkr },
  ],
  'Steeline RAD': [
    { name: 'style', label: 'Style', type: 'select', options: steelineRadStyle },
    { name: 'colour', label: 'Colour', type: 'select', options: standardColours },
    { name: 'finish', label: 'Finish', type: 'select', options: standardFinish },
    { name: 'doorHeight', label: 'Door Height', type: 'number' },
    { name: 'doorWidth', label: 'Door Width', type: 'number' },
    { name: 'woodGrainOrSmooth', label: 'Wood Grain or Smooth', type: 'text' },
    { name: 'fittings', label: 'Fittings', type: 'select', options: ['LHR', 'STD'] },
    { name: 'keyedAlike', label: 'Keyed Alike', type: 'select', options: ['Yes', 'No'] },
    { name: 'keyedDifferent', label: 'Keyed Different', type: 'select', options: ['Yes', 'No'] },
    { name: 'shootBolts', label: 'Shoot Bolts', type: 'select', options: ['Yes', 'No'] },
    { name: 'windowType', label: 'Window Type', type: 'select', options: [] },
    { name: 'taperVilo', label: 'Taper (Vilo)', type: 'select', options: ['Yes', 'No'] },
    { name: 'notched', label: 'Notched', type: 'select', options: ['Yes', 'No'] },
    { name: 'steelWrapForTransport', label: 'Steel Wrap for Transport', type: 'select', options: ['Yes', 'No'] },
    { name: 'packForTransport', label: 'Pack for Transport', type: 'select', options: ['Yes', 'No'] },
    { name: 'hardware', label: 'Hardware', type: 'select', options: ['Brick Fix', 'Steel Fix'] },
    { name: 'locking', label: 'Locking', type: 'select', options: ['Centre Lift Lock', 'No Lock'] },
    { name: 'motor', label: 'Motor', type: 'text' },
    { name: 'jambs', label: 'Jambs', type: 'select', options: standardJambs },
    { name: 'covers', label: 'Covers', type: 'select', options: standardCovers },
    { name: 'pelmet', label: 'Pelmet', type: 'select', options: standardPelmet },
    { name: 'brushSeals', label: 'Brush Seals', type: 'select', options: standardBrushSeals },
    { name: 'ekr', label: 'EKR', type: 'select', options: standardEkr },
  ],
  'Danmar Custom': [
    { name: 'style', label: 'Style', type: 'select', options: danmarCustomStyle },
    { name: 'colour', label: 'Colour', type: 'select', options: danmarColours },
    { name: 'timberlook', label: 'Timberlook', type: 'select', options: danmarTimberlooks },
    { name: 'finish', label: 'Finish', type: 'select', options: standardFinish },
    { name: 'taper', label: 'Taper', type: 'select', options: standardTaper },
    { name: 'hardware', label: 'Hardware', type: 'select', options: standardHardware },
    { name: 'motor', label: 'Motor', type: 'text' },
    { name: 'jambs', label: 'Jambs', type: 'select', options: standardJambs },
    { name: 'covers', label: 'Covers', type: 'select', options: standardCovers },
    { name: 'pelmet', label: 'Pelmet', type: 'select', options: standardPelmet },
    { name: 'brushSeals', label: 'Brush Seals', type: 'select', options: standardBrushSeals },
    { name: 'ekr', label: 'EKR', type: 'select', options: standardEkr },
  ],
  'Metrol RAD': [
    { name: 'style', label: 'Style', type: 'select', options: metrolRadStyle },
    { name: 'colour', label: 'Colour', type: 'select', options: standardColours },
    { name: 'finish', label: 'Finish', type: 'select', options: standardFinish },
    { name: 'taper', label: 'Taper', type: 'select', options: standardTaper },
    { name: 'hardware', label: 'Hardware', type: 'select', options: ['Brick Fix', 'Steel Fix'] },
    { name: 'locking', label: 'Locking', type: 'select', options: ['Centre Lift Lock', 'No Lock'] },
    { name: 'motor', label: 'Motor', type: 'text' },
    { name: 'jambs', label: 'Jambs', type: 'select', options: standardJambs },
    { name: 'covers', label: 'Covers', type: 'select', options: standardCovers },
    { name: 'pelmet', label: 'Pelmet', type: 'select', options: standardPelmet },
    { name: 'brushSeals', label: 'Brush Seals', type: 'select', options: standardBrushSeals },
    { name: 'ekr', label: 'EKR', type: 'select', options: standardEkr },
  ],
}
